version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./M1/project-root/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nodejs:
    build:
      context: ./M1/project-root
      dockerfile: Dockerfile
    container_name: library_api
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: library_user
      DB_PASSWORD: library_password
      DB_NAME: library_db
      JWT_SECRET: library_app_jwt_secret_key_for_development
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./M1/project-root:/app
      - /app/node_modules
    networks:
      - app-network
    command: sh -c "/wait-for-it.sh mysql 3306 && node src/index.js"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
