version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: library_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=library_db
    volumes:
      - ./src/config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  api:
    image: node:18-alpine
    container_name: library_api_new
    volumes:
      - ./:/app:rw
    working_dir: /app
    command: sh -c "npm install bcryptjs && npm install passport passport-google-oauth20 node-fetch@2 && node index.js"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=library_mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=library_db
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRATION=60
      - REFRESH_TOKEN_EXPIRATION=7
      - GOOGLE_CLIENT_ID=546036603143-scv9c0k6n8u4l3nhp78vtqthj8vc6qve.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://localhost:3000/api/oauth/google/callback
    depends_on:
      - mysql
    restart: unless-stopped