version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build: .  # Corrigido: use apenas 'build: .' em vez de context e dockerfile
    container_name: library_api_new
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: library_mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: library_db
      JWT_SECRET: your_jwt_secret_key
      JWT_EXPIRATION: 1h
      REFRESH_TOKEN_EXPIRATION: 7d
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge